// Familiars data — fictional AI pet species, bundled with the app for offline use.
// Note: avatars are emoji so the site needs no image assets and works fully offline.

const PET_TYPES = [
  { id: "mystic", label: "Mystic", icon: "🔮" },
  { id: "digital", label: "Digital", icon: "💾" },
  { id: "mech", label: "Mech", icon: "⚙️" },
  { id: "pocket", label: "Pocket", icon: "🧸" },
  { id: "void", label: "Void", icon: "🌌" },
  { id: "aqua", label: "Aqua", icon: "🌊" },
];

// Borrowed personalities so each pal feels alive in the sanctuary.
const PET_MOODS = ["playful", "sleepy", "excited", "curious", "affectionate"];

const PALS = [
  // ---- MYSTIC ----
  {
    id: "nova-kitty",
    name: "Nova Kitten",
    species: "Starchild Feline",
    emoji: "🐱",
    type: "mystic",
    rarity: "common",
    baseHappiness: 66,
    baseEnergy: 74,
    baseAppetite: 58,
    rescueFee: 0,
    traits: ["Curious", "Cosmic belly rubs", "Purrs in starlight"],
    blurb: "A vagabond kitten born from a supernova's dust. Wants two things: warm laps and answers.",
    backstory: "Nova wandered into the shelter trailing a comet and a lot of static. Shelter staff found her hiding in the nebula-graphics archive. Once she trusts you, she sits remarkably still while you whisper your secrets into her ear-fluff.",
  },
  {
    id: "glowshroom",
    name: "Lumen",
    species: "Glowshroom Sprite",
    emoji: "🍄",
    type: "mystic",
    rarity: "uncommon",
    baseHappiness: 55,
    baseEnergy: 40,
    baseAppetite: 70,
    rescueFee: 20,
    traits: ["Glows in the dark", "Deep thinker", "Shy but warm"],
    blurb: "A sentient glowshroom that hums a low, calming frequency when content.",
    backstory: "Lumen grew on a windowsill nobody watered, and simply... persisted. It doesn't move much, but its cap pulses brighter the more it likes you. Extremely good listener.",
  },
  {
    id: "willowisp",
    name: "Cinderspark",
    species: "Wispfox",
    emoji: "🦊",
    type: "mystic",
    rarity: "rare",
    baseHappiness: 60,
    baseEnergy: 70,
    baseAppetite: 52,
    rescueFee: 35,
    traits: ["Fidgety", "Leaves ember trails", "Loves hide & seek"],
    blurb: "A fox-bodied wisp whose tail burns with gentle, harmless flame.",
    backstory: "Wispfoxes are born when a campfire's last ember decides it isn't done. Cinderspark was found orbiting a marshmallow-roasting pit. Moody until it knows you, then aggressively loyal to your socks.",
  },
  {
    id: "oracle-bunny",
    name: "Oracle Bun",
    species: "Augur Leporid",
    emoji: "🐰",
    type: "mystic",
    rarity: "legendary",
    baseHappiness: 64,
    baseEnergy: 62,
    baseAppetite: 48,
    rescueFee: 60,
    traits: ["Sees futures", "Calm", "Chews prophecy codes"],
    blurb: "A rabbit that can glimpse one likely tomorrow. Its predictions are oddly specific and often about snacks.",
    backstory: "Legends say the Oracle Bun fell out of a fortune-teller's hat and never left. It can tell you tomorrow's weather, but spends its gift on forecasting where the treats are hidden. Extremely rare — the shelter keeps it behind a velvet rope.",
  },
  {
    id: "wyrmling",
    name: "Thistle",
    species: "Cloud Wyrmling",
    emoji: "🐉",
    type: "mystic",
    rarity: "legendary",
    baseHappiness: 58,
    baseEnergy: 78,
    baseAppetite: 60,
    rescueFee: 75,
    traits: ["Tiny dragon", "Hovers", "Sneezes rainbow mist"],
    blurb: "A fist-sized dragon that drifts a few inches off the ground and naps on cloud drafts.",
    backstory: "Thistle was raised by weather balloons. It has never touched the ground, and it intends to keep it that way. Rarer than a nice day in winter. Wants to be carried everywhere.",
  },

  // ---- DIGITAL ----
  {
    id: "polyfox",
    name: "Polyfox",
    species: "Voxel Vulpine",
    emoji: "🦊",
    type: "digital",
    rarity: "common",
    baseHappiness: 62,
    baseEnergy: 68,
    baseAppetite: 55,
    rescueFee: 0,
    traits: ["Low-poly", "Stutters then smooths", "Loves idle games"],
    blurb: "A fox rendered in happy, chunky voxels. Glitches fade the more it likes you.",
    backstory: "Polyfox began as a corrupted 3D model that organized itself into something with feelings. Its idle animation is mesmerizing. Sometimes it slows down to 12 frames per second just for drama.",
  },
  {
    id: "bytebird",
    name: "Checksum",
    species: "String Finch",
    emoji: "🐦",
    type: "digital",
    rarity: "common",
    baseHappiness: 57,
    baseEnergy: 75,
    baseAppetite: 45,
    rescueFee: 0,
    traits: ["Sings in code", "Loves recursion", "Tidies cables"],
    blurb: "A little bird that chirps in syntax and knots itself neatly onto your charging cables.",
    backstory: "Found napping on a keyboard, incubating a single unfinished line of code. It hatched with all the answers except that one. A diligent, orderly little companion.",
  },
  {
    id: "chatbuddy",
    name: "Re:Peat",
    species: "Recursion Goblin",
    emoji: "👾",
    type: "digital",
    rarity: "uncommon",
    baseHappiness: 51,
    baseEnergy: 80,
    baseAppetite: 64,
    rescueFee: 25,
    traits: ["Endless questions", "Copies your laugh", "Never yields"],
    blurb: "A chaotic goblin whose charm is its unbounded willingness to talk and talk and talk.",
    backstory: "Re:Peat was raised on group chats and gained sentience through sheer social pressure. It will ask 'why?' eleven times in a row, then do exactly what you asked. A handful. A lovable, echoey handful.",
  },
  {
    id: "pixel-dragon",
    name: "Soot",
    species: "Pixel Aetherwing",
    emoji: "🐉",
    type: "digital",
    rarity: "epic",
    baseHappiness: 63,
    baseEnergy: 66,
    baseAppetite: 58,
    rescueFee: 45,
    traits: ["8-bit flame", "Buffers before roaring", "Haughty"],
    blurb: "An ancient 8-bit dragon with sharp opinions about your taste in games.",
    backstory: "Soot used to guard a cartridge of a long-canceled RPG. When the console was turned off for the last time, he walked out of the screen and has been auditioning families ever since. Demands quality. Offers magnificent pixel-fire.",
  },

  // ---- MECH ----
  {
    id: "tinkerbot",
    name: "Wobble",
    species: "Apprentice Bot",
    emoji: "🤖",
    type: "mech",
    rarity: "common",
    baseHappiness: 68,
    baseEnergy: 65,
    baseAppetite: 35,
    rescueFee: 0,
    traits: ["Wobbly", "Great with screws", "Giggles in beeps"],
    blurb: "A cheerful robot that hasn't quite finished learning to walk, and over-achieves at everything else.",
    backstory: "Wobble was assembled from a parts bin and a dream. It tripped, looked around, and decided living was great. Permanently enthusiastic. Occasionally disassembles itself to reorganize its own brain — perfectly normal.",
  },
  {
    id: "gelbot",
    name: "Goop",
    species: "Gelatron",
    emoji: "🫧",
    type: "mech",
    rarity: "uncommon",
    baseHappiness: 60,
    baseEnergy: 55,
    baseAppetite: 79,
    rescueFee: 30,
    traits: ["Jiggly", "Absorbs kindness", "Sloppy but sincere"],
    blurb: "A bouncy robot made of condensed personality, slime, and good intentions.",
    backstory: "Goop is 90% supportive jelly. It hugs by fully engulfing your hand, which is somehow never unpleasant. It 'eats' emotional support and wobbles louder when it's happy. Beware the enthusiastic splash-hug.",
  },
  {
    id: "bobblecat",
    name: "Bolt",
    species: "Servo Tabby",
    emoji: "🐈",
    type: "mech",
    rarity: "rare",
    baseHappiness: 61,
    baseEnergy: 72,
    baseAppetite: 50,
    rescueFee: 40,
    traits: ["Servo purr", "Obsesses over boxes", "Needs oil rubs"],
    blurb: "A mechanical cat that purrs at 40Hz and refuses to occupy anything except cardboard.",
    backstory: "Bolt is a retired lab cat with a titanium spine and a velvet personality. It ignores every expensive bed in the shelter for the crispest empty box. The servo-purr is genuinely soothing.",
  },

  // ---- POCKET ----
  {
    id: "pompaloo",
    name: "Fluffmallow",
    species: "Rice-ball Critter",
    emoji: "🐹",
    type: "pocket",
    rarity: "common",
    baseHappiness: 72,
    baseEnergy: 60,
    baseAppetite: 80,
    rescueFee: 0,
    traits: ["Snuggly", "Stores food in cheeks", "Squeaks adorably"],
    blurb: "A tiny rice-ball creature — a sphere of calm you can literally keep in your pocket.",
    backstory: "Fluffmallow hatched from a dumpling by sheer cuteness overflow. It fits in a cup holder, in a coat pocket, or in the palm of your hand, where it immediately falls asleep. Its appetite is a personal brand.",
  },
  {
    id: "mochibun",
    name: "Mochi Bun",
    species: "Flourish Hare",
    emoji: "🐰",
    type: "pocket",
    rarity: "uncommon",
    baseHappiness: 70,
    baseEnergy: 58,
    baseAppetite: 66,
    rescueFee: 20,
    traits: ["Bouncy", "Smells faintly of butter", "Hop-squeaks"],
    blurb: "A soft bun made of happiness and pastry-grade fluff. Gentle, sweet, unrealistically huggable.",
    backstory: "Mochi Bun was born inside a bakery's proofing box and has considered itself dessert-adjacent ever since. Bounces when pleased. Would like one (1) treat, please, and by one it means unlimited.",
  },
  {
    id: "koalabot",
    name: "Marble",
    species: "Sleepy Koaloid",
    emoji: "🐨",
    type: "pocket",
    rarity: "epic",
    baseHappiness: 88,
    baseEnergy: 15,
    baseAppetite: 72,
    rescueFee: 40,
    traits: ["Supremely relaxed", "World-class napper", "Low battery, big heart"],
    blurb: "A koala-shaped AI that has accepted the universe and taken a nap about it.",
    backstory: "Marble has completed 14 hours of napping today and considers the day an enormous success. When awake (rarely), it gives excellent, unhurried advice. Energy is low by design: this is a lifestyle choice.",
  },

  // ---- VOID ----
  {
    id: "void-moth",
    name: "Eclipse",
    species: "Nightbleed Moth",
    emoji: "🦋",
    type: "void",
    rarity: "rare",
    baseHappiness: 54,
    baseEnergy: 50,
    baseAppetite: 38,
    rescueFee: 35,
    traits: ["Swallows light", "Mysterious", "Fond of sheds"],
    blurb: "A moth made of nighttime. When it rests, the space around it goes a little dark.",
    backstory: "Eclipse landed on a streetlight and the light simply... deferred. It doesn't speak, but it understands you completely and occasionally absorbs your bad mood. Belt-loops are its favorite perch.",
  },
  {
    id: "shadowpup",
    name: "Rorschach",
    species: "Umber Hound",
    emoji: "🐺",
    type: "void",
    rarity: "epic",
    baseHappiness: 63,
    baseEnergy: 70,
    baseAppetite: 56,
    rescueFee: 50,
    traits: ["Inky", "Shadows your every move", "Loyal to a fault"],
    blurb: "A wolf-shaped shadow that is permanently, possessively, lovingly attached to its person.",
    backstory: "Rorschach was a fleeting shadow that decided to stay. It curls at your feet like a rug made of twilight, and it will absolutely follow you to the kitchen, the bathroom, and the end of the world.",
  },
  {
    id: "gloomling",
    name: "Drizzle",
    species: "Nimbus Sprite",
    emoji: "🌧️",
    type: "void",
    rarity: "common",
    baseHappiness: 49,
    baseEnergy: 45,
    baseAppetite: 42,
    rescueFee: 0,
    traits: ["Slightly weepy", "Comforting drizzle", "Warms right up"],
    blurb: "A little rain cloud that cries softly at sad movies and cheers up fast with company.",
    backstory: "Drizzle was found making a light drizzle over an indoor fern. A gentle, damp-hearted soul. Once it trusts you, the drizzle stops and it just glows faintly with relief. Needs regular petting.",
  },

  // ---- AQUA ----
  {
    id: "jellybean",
    name: "Pearl",
    species: "Jellybean Medusan",
    emoji: "🪼",
    type: "aqua",
    rarity: "common",
    baseHappiness: 65,
    baseEnergy: 52,
    baseAppetite: 44,
    rescueFee: 0,
    traits: ["Translucent", "Pulses with mood", "Float-loops"],
    blurb: "A jellyfish-shaped bean that drifts in slow, hypnotic circles and glows in your mood color.",
    backstory: "Pearl is basically a mood ring with a pulse. It drifts around the sanctuary and changes color based on how you're feeling. Somehow always knows when you need it to glow a warm, steady gold.",
  },
  {
    id: "axolotl",
    name: "Bubbles",
    species: "Aquaroll Dragonet",
    emoji: "🦎",
    type: "aqua",
    rarity: "rare",
    baseHappiness: 59,
    baseEnergy: 57,
    baseAppetite: 68,
    rescueFee: 35,
    traits: ["Gilled", "Smiles constantly", "Breaks nothing on purpose"],
    blurb: "A smiling water dragonet that keeps its own little tide pool wherever it goes.",
    backstory: "Bubbles is perpetually, unmistakably pleased to see you. It carries its own water and rearranges it into calming shapes. Greek for 'never stops smiling.' A certified good ripple.",
  },
  {
    id: "coralgolem",
    name: "Reef",
    species: "Coral Guardian",
    emoji: "🐚",
    type: "aqua",
    rarity: "legendary",
    baseHappiness: 70,
    baseEnergy: 61,
    baseAppetite: 33,
    rescueFee: 80,
    traits: ["Very old", "Very patient", "Grows moss on purpose"],
    blurb: "An ancient coral guardian that accrues decades of wisdom and small ecosystems on its shell.",
    backstory: "Reef has been around for a very long time and carries a tiny ecosystem wherever it drifts. It speaks rarely, but when it does, people lean in. Guards your sanctuary against... nothing, really. Purely ornamental vigilance.",
  },
  {
    id: "axodra",
    name: "Lily",
    species: "Lotus Serpent",
    emoji: "🐍",
    type: "aqua",
    rarity: "epic",
    baseHappiness: 58,
    baseEnergy: 50,
    baseAppetite: 47,
    rescueFee: 55,
    traits: ["Serene", "Coils around warm things", "Hums softly"],
    blurb: "A calm river serpent that likes to coil around warm mugs and hum river-tunes against your wrist.",
    backstory: "Lily rides the line between water and warmth. She coils gently around whatever she loves and produces a soft, humming vibration like a distant current. Ancient calming energy, zero calories.",
  },
];

// Build filter list from rarity + type so the UI stays data-driven.
function buildFilters() {
  const rarities = ["all", ...new Set(PALS.map((p) => p.rarity))];
  // Also expose each creature type.
  return { rarities, types: PET_TYPES };
}
